export interface DeliveryCity {
    name: string;
    home_delivery: number;
    desk_delivery: number | null;
}

export const DELIVERY_CITIES: DeliveryCity[] = [
    { name: "Adrar", home_delivery: 1650, desk_delivery: 850 },
    { name: "Chlef", home_delivery: 700, desk_delivery: 450 },
    { name: "Laghouat", home_delivery: 850, desk_delivery: 450 },
    { name: "Oum El Bouaghi", home_delivery: 850, desk_delivery: 450 },
    { name: "Batna", home_delivery: 850, desk_delivery: 450 },
    { name: "Béjaïa", home_delivery: 850, desk_delivery: 450 },
    { name: "Biskra", home_delivery: 850, desk_delivery: 650 },
    { name: "Béchar", home_delivery: 1200, desk_delivery: 650 },
    { name: "Blida", home_delivery: 650, desk_delivery: 400 },
    { name: "Bouira", home_delivery: 650, desk_delivery: 450 },
    { name: "Tamanrasset", home_delivery: 1800, desk_delivery: 1000 },
    { name: "Tébessa", home_delivery: 850, desk_delivery: 450 },
    { name: "Tlemcen", home_delivery: 850, desk_delivery: 450 },
    { name: "Tiaret", home_delivery: 850, desk_delivery: 450 },
    { name: "Tizi Ouzou", home_delivery: 650, desk_delivery: 450 },
    { name: "Alger", home_delivery: 450, desk_delivery: 300 },
    { name: "Djelfa", home_delivery: 850, desk_delivery: 450 },
    { name: "Jijel", home_delivery: 850, desk_delivery: 450 },
    { name: "Sétif", home_delivery: 850, desk_delivery: 450 },
    { name: "Saïda", home_delivery: 850, desk_delivery: 450 },
    { name: "Skikda", home_delivery: 850, desk_delivery: 450 },
    { name: "Sidi Bel Abbès", home_delivery: 850, desk_delivery: 450 },
    { name: "Annaba", home_delivery: 850, desk_delivery: 450 },
    { name: "Guelma", home_delivery: 850, desk_delivery: 450 },
    { name: "Constantine", home_delivery: 850, desk_delivery: 450 },
    { name: "Médéa", home_delivery: 650, desk_delivery: 450 },
    { name: "Mostaganem", home_delivery: 850, desk_delivery: 450 },
    { name: "M'Sila", home_delivery: 850, desk_delivery: 450 },
    { name: "Mascara", home_delivery: 850, desk_delivery: 450 },
    { name: "Ouargla", home_delivery: 1000, desk_delivery: 500 },
    { name: "Oran", home_delivery: 850, desk_delivery: 450 },
    { name: "El Bayadh", home_delivery: 850, desk_delivery: 450 },
    { name: "Illizi", home_delivery: 1700, desk_delivery: 850 },
    { name: "Bordj Bou Arreridj", home_delivery: 650, desk_delivery: 450 },
    { name: "Boumerdès", home_delivery: 650, desk_delivery: 400 },
    { name: "El Tarf", home_delivery: 850, desk_delivery: 550 },
    { name: "Tindouf", home_delivery: 1650, desk_delivery: null },
    { name: "Tissemsilt", home_delivery: 850, desk_delivery: 450 },
    { name: "El Oued", home_delivery: 950, desk_delivery: 600 },
    { name: "Khenchela", home_delivery: 850, desk_delivery: 450 },
    { name: "Souk Ahras", home_delivery: 850, desk_delivery: 450 },
    { name: "Tipaza", home_delivery: 650, desk_delivery: 450 },
    { name: "Mila", home_delivery: 850, desk_delivery: 450 },
    { name: "Aïn Defla", home_delivery: 650, desk_delivery: 450 },
    { name: "Naâma", home_delivery: 950, desk_delivery: 500 },
    { name: "Aïn Témouchent", home_delivery: 850, desk_delivery: 450 },
    { name: "Ghardaïa", home_delivery: 950, desk_delivery: 650 },
    { name: "Relizane", home_delivery: 850, desk_delivery: 450 },
    { name: "Timimoun", home_delivery: 1650, desk_delivery: null },
    { name: "Bordj Badji Mokhtar", home_delivery: 1600, desk_delivery: null },
    { name: "Ouled Djellal", home_delivery: 950, desk_delivery: null },
    { name: "Béni Abbès", home_delivery: 1300, desk_delivery: null },
    { name: "In Salah", home_delivery: 1650, desk_delivery: 850 },
    { name: "In Guezzam", home_delivery: 1500, desk_delivery: 750 },
    { name: "Touggourt", home_delivery: 950, desk_delivery: 500 },
    { name: "Djanet", home_delivery: 2000, desk_delivery: 1000 },
    { name: "El M'Ghair", home_delivery: 950, desk_delivery: null },
    { name: "El Meniaa", home_delivery: 950, desk_delivery: 500 }
];
