export interface Product {
    id: string;
    name: string;
    price: number;
    originalPrice?: number;
    image: string;
    images: Array<{ id: string; url: string; alt: string }>;
    category: string;
    availableSizes: string[];
    description: string;
    isAvailable: boolean;
    rating: number;
    status: 'Available' | 'Out-of-stock';
    availableColors: Array<{ name: string; hex: string }>;
    gender: 'MEN' | 'WOMEN' | 'UNISEX';
    stock: number;
    sales: number;
    date: string;
    colors?: string[];
}

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Denim baggy jeans',
        price: 3500.00,
        originalPrice: 4500.00,
        image: '/assets/product.png',
        images: [{ id: '1-1', url: '/assets/product.png', alt: 'Denim baggy jeans' }],
        category: 'Jeans',
        availableSizes: ['S', 'M', 'L', 'XL'],
        colors: ['Blue', 'Black', 'Gray'],
        availableColors: [{ name: 'Blue', hex: '#0000FF' }],
        description: 'Classic denim baggy jeans with a comfortable fit.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 10,
        sales: 5,
        date: '2025-01-01',
        rating: 4.5,
    },
    {
        id: '2',
        name: 'Red Polo Shirt',
        price: 2500.00,
        image: '/assets/product.png',
        images: [{ id: '2-1', url: '/assets/product.png', alt: 'Red Polo Shirt' }],
        category: 'Shirts',
        availableSizes: ['M', 'L', 'XL'],
        colors: ['Red', 'White', 'Navy'],
        availableColors: [{ name: 'Red', hex: '#FF0000' }],
        description: 'Vibrant red polo shirt made from breathable cotton.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 15,
        sales: 8,
        date: '2025-01-02',
        rating: 4.2,
    },
    {
        id: '3',
        name: 'Beige Oversized Shirt',
        price: 3200.00,
        originalPrice: 4000.00,
        image: '/assets/product.png',
        images: [{ id: '3-1', url: '/assets/product.png', alt: 'Beige Oversized Shirt' }],
        category: 'Shirts',
        availableSizes: ['S', 'M', 'L'],
        colors: ['Beige', 'White', 'Gray'],
        availableColors: [{ name: 'Beige', hex: '#F5F5DC' }],
        description: 'Relaxed fit beige shirt, perfect for casual outings.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 20,
        sales: 12,
        date: '2025-01-03',
        rating: 4.7,
    },
    {
        id: '4',
        name: 'Blue Linen Shirt',
        price: 2800.00,
        image: '/assets/product.png',
        images: [{ id: '4-1', url: '/assets/product.png', alt: 'Blue Linen Shirt' }],
        category: 'Shirts',
        availableSizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Blue', 'White', 'Navy'],
        availableColors: [{ name: 'Blue', hex: '#0000FF' }],
        description: 'Cool and airy blue linen shirt for summer days.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 25,
        sales: 15,
        date: '2025-01-04',
        rating: 4.4,
    },
    {
        id: '5',
        name: 'White Linen Shirt',
        price: 2900.00,
        originalPrice: 3500.00,
        image: '/assets/product.png',
        images: [{ id: '5-1', url: '/assets/product.png', alt: 'White Linen Shirt' }],
        category: 'Shirts',
        availableSizes: ['S', 'M', 'L', 'XL'],
        colors: ['White', 'Beige', 'Blue'],
        availableColors: [{ name: 'White', hex: '#FFFFFF' }],
        description: 'Classic white linen shirt, a wardrobe essential.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 30,
        sales: 20,
        date: '2025-01-05',
        rating: 4.6,
    },
    {
        id: '6',
        name: 'Beige Knitted Polo',
        price: 3800.00,
        image: '/assets/product.png',
        images: [{ id: '6-1', url: '/assets/product.png', alt: 'Beige Knitted Polo' }],
        category: 'Polos',
        availableSizes: ['M', 'L'],
        colors: ['Beige', 'Brown', 'Gray'],
        availableColors: [{ name: 'Beige', hex: '#F5F5DC' }],
        description: 'Textured beige knitted polo for a sophisticated look.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 12,
        sales: 6,
        date: '2025-01-06',
        rating: 4.8,
    },
    {
        id: '7',
        name: 'White Short Sleeve Shirt',
        price: 2200.00,
        image: '/assets/product.png',
        images: [{ id: '7-1', url: '/assets/product.png', alt: 'White Short Sleeve Shirt' }],
        category: 'Shirts',
        availableSizes: ['S', 'M', 'L'],
        colors: ['White', 'Black', 'Gray'],
        availableColors: [{ name: 'White', hex: '#FFFFFF' }],
        description: 'Crisp white short sleeve shirt for a clean style.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 40,
        sales: 25,
        date: '2025-01-07',
        rating: 4.3,
    },
    {
        id: '8',
        name: 'Brown Zip Jacket',
        price: 5500.00,
        originalPrice: 6500.00,
        image: '/assets/product.png',
        images: [{ id: '8-1', url: '/assets/product.png', alt: 'Brown Zip Jacket' }],
        category: 'Jackets',
        availableSizes: ['M', 'L', 'XL'],
        colors: ['Brown', 'Black', 'Navy'],
        availableColors: [{ name: 'Brown', hex: '#A52A2A' }],
        description: 'Stylish brown zip jacket for cooler evenings.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 18,
        sales: 9,
        date: '2025-01-08',
        rating: 4.9,
    },
    {
        id: '9',
        name: 'Beige Trucker Jacket',
        price: 4800.00,
        image: '/assets/product.png',
        images: [{ id: '9-1', url: '/assets/product.png', alt: 'Beige Trucker Jacket' }],
        category: 'Jackets',
        availableSizes: ['S', 'M', 'L', 'XL'],
        colors: ['Beige', 'Brown', 'Black'],
        availableColors: [{ name: 'Beige', hex: '#F5F5DC' }],
        description: 'Versatile beige trucker jacket that goes with everything.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 14,
        sales: 7,
        date: '2025-01-09',
        rating: 4.5,
    },
    {
        id: '10',
        name: 'Black Trousers',
        price: 3000.00,
        image: '/assets/product.png',
        images: [{ id: '10-1', url: '/assets/product.png', alt: 'Black Trousers' }],
        category: 'Trousers',
        availableSizes: ['30', '32', '34', '36'],
        colors: ['Black', 'Navy', 'Gray'],
        availableColors: [{ name: 'Black', hex: '#000000' }],
        description: 'Formal black trousers for office or events.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 35,
        sales: 18,
        date: '2025-01-10',
        rating: 4.4,
    },
    {
        id: '11',
        name: 'Brown Short Sleeve Shirt',
        price: 2600.00,
        image: '/assets/product.png',
        images: [{ id: '11-1', url: '/assets/product.png', alt: 'Brown Short Sleeve Shirt' }],
        category: 'Shirts',
        availableSizes: ['M', 'L', 'XL'],
        colors: ['Brown', 'Beige', 'White'],
        availableColors: [{ name: 'Brown', hex: '#A52A2A' }],
        description: 'Casual brown short sleeve shirt.',
        isAvailable: true,
        status: 'Available',
        gender: 'UNISEX',
        stock: 22,
        sales: 11,
        date: '2025-01-11',
        rating: 4.1,
    },
    {
        id: '12',
        name: 'Navy Zip Sweater',
        price: 4200.00,
        originalPrice: 5000.00,
        image: '/assets/product.png',
        images: [{ id: '12-1', url: '/assets/product.png', alt: 'Navy Zip Sweater' }],
        category: 'Sweaters',
        availableSizes: ['M', 'L', 'XL'],
        colors: ['Navy', 'Black', 'Gray'],
        availableColors: [{ name: 'Navy', hex: '#000080' }],
        description: 'Cozy navy zip sweater for layering.',
        isAvailable: true,
        status: 'Available',
        gender: 'MEN',
        stock: 16,
        sales: 8,
        date: '2025-01-12',
        rating: 4.7,
    },
];
