export interface Product {
    id: string;
    title: string;
    price: number;
    originalPrice?: number;
    image: string;
    category: string;
    size: string[];
    colors?: string[];
    description: string;
    availability: boolean;
    rating: number;
}

export const mockProducts: Product[] = [
    {
        id: '1',
        title: 'Denim baggy jeans',
        price: 3500.00,
        originalPrice: 4500.00,
        image: '/assets/product.png',
        category: 'Jeans',
        size: ['S', 'M', 'L', 'XL'],
        colors: ['Blue', 'Black', 'Gray'],
        description: 'Classic denim baggy jeans with a comfortable fit.',
        availability: true,
        rating: 4.5,
    },
    {
        id: '2',
        title: 'Red Polo Shirt',
        price: 2500.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['M', 'L', 'XL'],
        colors: ['Red', 'White', 'Navy'],
        description: 'Vibrant red polo shirt made from breathable cotton.',
        availability: true,
        rating: 4.2,
    },
    {
        id: '3',
        title: 'Beige Oversized Shirt',
        price: 3200.00,
        originalPrice: 4000.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['S', 'M', 'L'],
        colors: ['Beige', 'White', 'Gray'],
        description: 'Relaxed fit beige shirt, perfect for casual outings.',
        availability: true,
        rating: 4.7,
    },
    {
        id: '4',
        title: 'Blue Linen Shirt',
        price: 2800.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['M', 'L', 'XL', 'XXL'],
        colors: ['Blue', 'White', 'Navy'],
        description: 'Cool and airy blue linen shirt for summer days.',
        availability: true,
        rating: 4.4,
    },
    {
        id: '5',
        title: 'White Linen Shirt',
        price: 2900.00,
        originalPrice: 3500.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['S', 'M', 'L', 'XL'],
        colors: ['White', 'Beige', 'Blue'],
        description: 'Classic white linen shirt, a wardrobe essential.',
        availability: true,
        rating: 4.6,
    },
    {
        id: '6',
        title: 'Beige Knitted Polo',
        price: 3800.00,
        image: '/assets/product.png',
        category: 'Polos',
        size: ['M', 'L'],
        colors: ['Beige', 'Brown', 'Gray'],
        description: 'Textured beige knitted polo for a sophisticated look.',
        availability: true,
        rating: 4.8,
    },
    {
        id: '7',
        title: 'White Short Sleeve Shirt',
        price: 2200.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['S', 'M', 'L'],
        colors: ['White', 'Black', 'Gray'],
        description: 'Crisp white short sleeve shirt for a clean style.',
        availability: true,
        rating: 4.3,
    },
    {
        id: '8',
        title: 'Brown Zip Jacket',
        price: 5500.00,
        originalPrice: 6500.00,
        image: '/assets/product.png',
        category: 'Jackets',
        size: ['M', 'L', 'XL'],
        colors: ['Brown', 'Black', 'Navy'],
        description: 'Stylish brown zip jacket for cooler evenings.',
        availability: true,
        rating: 4.9,
    },
    {
        id: '9',
        title: 'Beige Trucker Jacket',
        price: 4800.00,
        image: '/assets/product.png',
        category: 'Jackets',
        size: ['S', 'M', 'L', 'XL'],
        colors: ['Beige', 'Brown', 'Black'],
        description: 'Versatile beige trucker jacket that goes with everything.',
        availability: true,
        rating: 4.5,
    },
    {
        id: '10',
        title: 'Black Trousers',
        price: 3000.00,
        image: '/assets/product.png',
        category: 'Trousers',
        size: ['30', '32', '34', '36'],
        colors: ['Black', 'Navy', 'Gray'],
        description: 'Formal black trousers for office or events.',
        availability: true,
        rating: 4.4,
    },
    {
        id: '11',
        title: 'Brown Short Sleeve Shirt',
        price: 2600.00,
        image: '/assets/product.png',
        category: 'Shirts',
        size: ['M', 'L', 'XL'],
        colors: ['Brown', 'Beige', 'White'],
        description: 'Casual brown short sleeve shirt.',
        availability: true,
        rating: 4.1,
    },
    {
        id: '12',
        title: 'Navy Zip Sweater',
        price: 4200.00,
        originalPrice: 5000.00,
        image: '/assets/product.png',
        category: 'Sweaters',
        size: ['M', 'L', 'XL'],
        colors: ['Navy', 'Black', 'Gray'],
        description: 'Cozy navy zip sweater for layering.',
        availability: true,
        rating: 4.7,
    },
];
